"""update models

Revision ID: 18c369db0ae6
Revises: 5420975bfce7
Create Date: 2024-06-05 17:55:21.678116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c369db0ae6'
down_revision: Union[str, None] = '5420975bfce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamequestion',
    sa.Column('questionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questiontext', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('questionid'),
    schema='petsitters'
    )
    op.create_index(op.f('ix_petsitters_gamequestion_questionid'), 'gamequestion', ['questionid'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_gamequestion_questiontext'), 'gamequestion', ['questiontext'], unique=False, schema='petsitters')
    op.create_table('user',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('currentgamequestionid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    schema='petsitters'
    )
    op.create_index(op.f('ix_petsitters_user_currentgamequestionid'), 'user', ['currentgamequestionid'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_user_email'), 'user', ['email'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_user_fullname'), 'user', ['fullname'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_user_phone'), 'user', ['phone'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_user_profession'), 'user', ['profession'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_user_userid'), 'user', ['userid'], unique=False, schema='petsitters')
    op.create_table('gameanswer',
    sa.Column('answerid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questionid', sa.Integer(), nullable=True),
    sa.Column('answertext', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['questionid'], ['petsitters.gamequestion.questionid'], ),
    sa.PrimaryKeyConstraint('answerid'),
    sa.UniqueConstraint('answerid', 'questionid', name='unique_answer_question'),
    schema='petsitters'
    )
    op.create_index(op.f('ix_petsitters_gameanswer_answerid'), 'gameanswer', ['answerid'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_gameanswer_answertext'), 'gameanswer', ['answertext'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_gameanswer_questionid'), 'gameanswer', ['questionid'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_gameanswer_score'), 'gameanswer', ['score'], unique=False, schema='petsitters')
    op.create_table('useranswer',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('questionid', sa.Integer(), nullable=False),
    sa.Column('answertext', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['questionid'], ['petsitters.gamequestion.questionid'], ),
    sa.ForeignKeyConstraint(['userid'], ['petsitters.user.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'questionid'),
    sa.UniqueConstraint('userid', 'questionid', name='unique_user_question'),
    schema='petsitters'
    )
    op.create_index(op.f('ix_petsitters_useranswer_answertext'), 'useranswer', ['answertext'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_useranswer_questionid'), 'useranswer', ['questionid'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_useranswer_score'), 'useranswer', ['score'], unique=False, schema='petsitters')
    op.create_index(op.f('ix_petsitters_useranswer_userid'), 'useranswer', ['userid'], unique=False, schema='petsitters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_petsitters_useranswer_userid'), table_name='useranswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_useranswer_score'), table_name='useranswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_useranswer_questionid'), table_name='useranswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_useranswer_answertext'), table_name='useranswer', schema='petsitters')
    op.drop_table('useranswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_gameanswer_score'), table_name='gameanswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_gameanswer_questionid'), table_name='gameanswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_gameanswer_answertext'), table_name='gameanswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_gameanswer_answerid'), table_name='gameanswer', schema='petsitters')
    op.drop_table('gameanswer', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_user_userid'), table_name='user', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_user_profession'), table_name='user', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_user_phone'), table_name='user', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_user_fullname'), table_name='user', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_user_email'), table_name='user', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_user_currentgamequestionid'), table_name='user', schema='petsitters')
    op.drop_table('user', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_gamequestion_questiontext'), table_name='gamequestion', schema='petsitters')
    op.drop_index(op.f('ix_petsitters_gamequestion_questionid'), table_name='gamequestion', schema='petsitters')
    op.drop_table('gamequestion', schema='petsitters')
    # ### end Alembic commands ###
