"""add new field to GameQuestion

Revision ID: 907f43226796
Revises: 36e050a26136
Create Date: 2024-06-05 16:43:13.789244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907f43226796'
down_revision: Union[str, None] = '36e050a26136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamequestion',
    sa.Column('questionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questiontext', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('questionid')
    )
    op.create_index(op.f('ix_gamequestion_questionid'), 'gamequestion', ['questionid'], unique=False)
    op.create_index(op.f('ix_gamequestion_questiontext'), 'gamequestion', ['questiontext'], unique=False)
    op.create_table('user',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('currentgamequestionid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_user_currentgamequestionid'), 'user', ['currentgamequestionid'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_profession'), 'user', ['profession'], unique=False)
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=False)
    op.create_table('gameanswer',
    sa.Column('answerid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questionid', sa.Integer(), nullable=False),
    sa.Column('answertext', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['questionid'], ['gamequestion.questionid'], ),
    sa.PrimaryKeyConstraint('answerid', 'questionid'),
    sa.UniqueConstraint('answerid', 'questionid', name='unique_answer_question')
    )
    op.create_index(op.f('ix_gameanswer_answerid'), 'gameanswer', ['answerid'], unique=False)
    op.create_index(op.f('ix_gameanswer_answertext'), 'gameanswer', ['answertext'], unique=False)
    op.create_index(op.f('ix_gameanswer_questionid'), 'gameanswer', ['questionid'], unique=False)
    op.create_index(op.f('ix_gameanswer_score'), 'gameanswer', ['score'], unique=False)
    op.create_table('useranswer',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('questionid', sa.Integer(), nullable=False),
    sa.Column('answertext', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['questionid'], ['gamequestion.questionid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'questionid'),
    sa.UniqueConstraint('userid', 'questionid', name='unique_user_question')
    )
    op.create_index(op.f('ix_useranswer_answertext'), 'useranswer', ['answertext'], unique=False)
    op.create_index(op.f('ix_useranswer_questionid'), 'useranswer', ['questionid'], unique=False)
    op.create_index(op.f('ix_useranswer_score'), 'useranswer', ['score'], unique=False)
    op.create_index(op.f('ix_useranswer_userid'), 'useranswer', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useranswer_userid'), table_name='useranswer')
    op.drop_index(op.f('ix_useranswer_score'), table_name='useranswer')
    op.drop_index(op.f('ix_useranswer_questionid'), table_name='useranswer')
    op.drop_index(op.f('ix_useranswer_answertext'), table_name='useranswer')
    op.drop_table('useranswer')
    op.drop_index(op.f('ix_gameanswer_score'), table_name='gameanswer')
    op.drop_index(op.f('ix_gameanswer_questionid'), table_name='gameanswer')
    op.drop_index(op.f('ix_gameanswer_answertext'), table_name='gameanswer')
    op.drop_index(op.f('ix_gameanswer_answerid'), table_name='gameanswer')
    op.drop_table('gameanswer')
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.drop_index(op.f('ix_user_profession'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_currentgamequestionid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_gamequestion_questiontext'), table_name='gamequestion')
    op.drop_index(op.f('ix_gamequestion_questionid'), table_name='gamequestion')
    op.drop_table('gamequestion')
    # ### end Alembic commands ###
